---
- name: Install or remove package on remote hosts
  hosts: all
  become: true
  vars:
    action: install
  tasks:

  - name: Install package on remote host
    package:
      name: "{{ package }}"
      state: present           # You can install latest package by changing "present" value to "latest"
    when: action == "install"

  - name: Remove package on remote hosts
    package:
      name: "{{ package }}"
      state: absent
    when: action == "remove"
